name: Release

on:
  release:
    types: [released]

jobs:
  python-package:
    uses: ./.github/workflows/python-package.yml
  linux-build:
    uses: ./.github/workflows/build-and-release-linux.yml
  mac-build:
    uses: ./.github/workflows/build-and-release-mac.yml
  windows-build:
    uses: ./.github/workflows/build-and-release-windows.yml
